all:
	@(cd runtime; make --no-print-directory)
	@(cd server;  make --no-print-directory)
	@(cd storage; make --no-print-directory)
clean:
	@(cd runtime; make --no-print-directory clean)
	@(cd server;  make --no-print-directory clean)
	@(cd storage; make --no-print-directory clean)
