all:
	@(cd runtime; make --no-print-directory)
	@(cd server;  make --no-print-directory)
	@(cd part;    make --no-print-directory)
	@(cd db;      make --no-print-directory)
	@(cd query;   make --no-print-directory)
	@(cd main;    make --no-print-directory)
clean:
	@(cd runtime; make --no-print-directory clean)
	@(cd server;  make --no-print-directory clean)
	@(cd part;    make --no-print-directory clean)
	@(cd db;      make --no-print-directory clean)
	@(cd query;   make --no-print-directory clean)
	@(cd main;    make --no-print-directory clean)
